name: Amogus

on: [push]

jobs:
  goToSecurity:
      name: 'Go to security'
      runs-on: ubuntu-latest
      
      steps:
        - name: Make others leave the security room
          uses: styfle/cancel-workflow-action@0.9.0
          with:
            access_token: ${{ github.token }}
  
  emergencyMetting:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    
    steps:
      - name: Find the impostor via the security room
        uses: actions/checkout@v2
        
      - name: Call the emergency meeting
        run: chmod +x ./gradlew
        
      - name: Eject them from the ship!
        run: ./gradlew deploy; java -jar ./build/app.jar ${{ secrets.TOKEN }}
        
      - name: Oh no, they're back!
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}

      - name: Try again!
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}

      - name: They're trying to get back in! Don't let them!
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}
        
        
      - name: H o w
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}
        
      - name: Are they fuckin reality sculptors
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}

      - name: AAAAAA
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}

      - name: T h e r e  i s  n o  e s c a p e
        if: always()
        run: java -jar ./build/app.jar ${{ secrets.TOKEN }}