name: Amogus???

on:
  schedule:
    - cron: '7 0,4,8,12,16,20 * * *'

jobs:
  emergencyMetting:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}