name: Amogus???

on: 
  workflow_dispatch:
    inputs:
      amogi:
        description: 'idk'
        required: false
  schedule:
    - cron: '11 1,5,9,13,17,21 * * *'

jobs:
  emergencyMetting:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}

