name: Amogus???

on:
  workflow_dispatch
  schedule:
    '0 1,5,9,13,17,21 * * *'

jobs:
  emergencyMetting:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting1:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting2:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting3:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting2
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting4:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting3
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting5:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting4
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting6:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting5
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        uses: actions/cache@v1
        if: always()
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
  emergencyMetting7:
    name: 'Get rid of the impostor'
    runs-on: ubuntu-latest
    needs: emergencyMetting6
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        id: cache
        if: always()
        uses: actions/cache@v1
        with:
          path: ./saves
          key: ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ hashFiles('app/src/**') }}
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}
        
