name: Amogus???

on: 
  workflow_dispatch:
    inputs:
      amogi:
        description: 'idk'
        required: false
  schedule:
    - cron: '11 1,5,9,13,17,21 * * *'

jobs:
  deployment:
    name: 'Deployment'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy -Pgithub.token=${{ secrets.PACKAGES_TOKEN }}
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TOKEN }}

