name: TEST

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to test'
        required: true

jobs:
  emergencyMetting:
    name: 'test'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup jdk 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set experimental to true
        run: |
          sed -i "s/var experimental = false/var experimental = true/" app/src/main/kotlin/Vars.kt
      
      - name: Compile
        run: |
          chmod +x ./gradlew
          ./gradlew deploy
      
      - name: Run
        run: java -jar -Dkotlin.script.classpath=./build/app.jar ./build/app.jar ${{ secrets.TEST_TOKEN }}

